version: '3.7'


services:

  kubectl:
    environment:
      KUBECONFIG: /code/kubeconfig_datagov-k8s
  helm:
    environment:
      KUBECONFIG: /code/kubeconfig_datagov-k8s
  helmfile:
    environment:
      KUBECONFIG: /code/kubeconfig_datagov-k8s

volumes:
  aws-creds:
    name: aws-creds
  helm-config:
  helm-cache: