version: '3.7'


services:
  aws:
    image: abdennour/aws
    volumes:
      - .:/code
      - aws-creds:/root/.aws
    restart: "no"
    working_dir: /code
    environment:
      AWS_PROFILE: ${EKS_AWS_PROFILE}

  terraform:
    image: hashicorp/terraform:0.12.12
    volumes:
      - .:/code
      - aws-creds:/root/.aws
    working_dir: /code
    environment:
      AWS_PROFILE: ${EKS_AWS_PROFILE}

  kubectl: &kubectl
    image: abdennour/kubectl:v1.14.7-aws1.16.277
    volumes:
      - .:/code
      - aws-creds:/root/.aws:ro
    restart: "no"
    entrypoint: kubectl
    environment:
      AWS_PROFILE: ${EKS_AWS_PROFILE}
      KUBECONFIG: /code/kubeconfig_awesome
    ports:
    # machine : container
    - 8090:8090
  helm:
    <<: *kubectl
    image: abdennour/kubectl:v0.17.2-aws1.17.9-helm-3.0.2
    volumes:
    - testhelm:/root/.config/helm
    - testhelm2:/root/.cache/helm
    - .:/code
    - aws-creds:/root/.aws:ro
    entrypoint: sh

volumes:
  aws-creds:
    name: aws-creds
  testhelm:
  testhelm2: