autoDiscovery:
  clusterName: awesome
  enabled: true
awsRegion: ${aws_region}
cloudProvider: aws
rbac:
  create: true

serviceMonitor:
  enabled: true
  interval: 10s
  namespace: monitoring
  selector:
    release: prom